codegen ../epos.c epos_open_port_wrapper -args {'port_name'} ...
    -o epos_open_port -report

codegen ../epos.c epos_write_object_wrapper ...
    -args {uint64(0), uint16(0), uint8(0), uint8(0), uint32(0)} ...
    -o epos_write_object -report

codegen ../epos.c epos_read_object_wrapper ...
    -args {uint64(0), uint16(0), uint8(0), uint8(0)}...
    -o epos_read_object -report
